#!/bin/sh

for f in /config/yggdrasil.*.conf
do
  if [ "$f" == "/config/yggdrasil.*.conf" ];
  then
    continue
  fi

  mkdir -p /var/backups
  echo "Backing up configuration file to $f.`date +%Y%m%d`"
  cp $f $f.`date +%Y%m%d`
  echo "Normalising $f"
  /opt/vyatta/sbin/yggdrasil -useconffile $f.`date +%Y%m%d` -normaliseconf > $f
done

ln -fs /opt/vyatta/sbin/yggdrasilctl /usr/local/bin/yggdrasilctl
/opt/vyatta/sbin/vyatta-restart-yggdrasil
