#!/bin/sh
#
# vyatta-yggdrasil - A yggdrasil package for Ubiquiti EdgeOS, VyOS and other
# Vyatta-based systems.
# Copyright (C) 2018 Neil Alexander T.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ -n $1 ];
then
    if [ `cat /var/run/yggdrasil.$1.pid 2>/dev/null | wc -l` -gt 0 ];
    then
        echo -n "Stopping yggdrasil interface $1... "
        kill `cat /var/run/yggdrasil.$1.pid 2>/dev/null`
        if [ $? -eq 0 ]; then rm -f /var/run/yggdrasil.$1.pid &>/dev/null; echo "OK.";
        else rm -f /var/run/yggdrasil.$1.pid &>/dev/null; echo "failed."; fi
    fi

    if [ `ls /config/yggdrasil.*.conf 2>/dev/null | wc -l` -gt 0 ];
    then
        echo -n "Starting yggdrasil interface $1... "
        nohup nice -5 /opt/vyatta/sbin/yggdrasil -useconf &>/tmp/yggdrasil.$1.log < /config/yggdrasil.$1.conf &
        if [ $? -eq 0 ]; then echo $! > /var/run/yggdrasil.$1.pid; echo "OK.";
        else rm -f /var/run/yggdrasil.$1.pid &>/dev/null; echo "failed."; fi
    fi
else
    if [ `pgrep yggdrasil 2>/dev/null | wc -l` -gt 0 ];
    then
        echo -n "Stopping running yggdrasil interfaces... "
        (cat /var/run/yggdrasil.*.pid 2>/dev/null | xargs kill 2&>1)
        if [ $? -eq 0 ]; then rm -f /var/run/yggdrasil.*.pid &>/dev/null; echo "OK.";
        else rm -f /var/run/yggdrasil.$1.pid &>/dev/null; echo "failed."; fi
    fi

    if [ `ls /config/yggdrasil.*.conf 2>/dev/null | wc -l` -gt 0 ];
    then
        ls /config/yggdrasil.*.conf | awk -v FS="(yggdrasil.|.conf)" '{print $2}' | while read file;
        do
            echo -n "Starting yggdrasil interface $file... "
            nohup nice -5 /opt/vyatta/sbin/yggdrasil -useconf &>/tmp/yggdrasil.$1.log < /config/yggdrasil.$file.conf &
            if [ $? -eq 0 ]; then echo $! > /var/run/yggdrasil.$file.pid; echo "OK.";
            else rm -f /var/run/yggdrasil.$1.pid &>/dev/null; echo "failed."; fi
        done
    fi
fi
