#!/bin/sh
#
# vyatta-yggdrasil - A yggdrasil package for Ubiquiti EdgeOS, VyOS and other
# Vyatta-based systems.
# Copyright (C) 2018 Neil Alexander T.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ ! -z $1 ];
then
    if [ `pgrep -fc "yggdrasil -useconffile.*$1"` -gt 0 ];
    then
        pgrep -f "yggdrasil -useconffile.*$1" | while read pid;
        do
            echo -n "Stopping yggdrasil interface $1... "
            kill $pid
            if [ $? -eq 0 ]; then echo "OK."; else echo "failed."; fi
        done
    fi

    if [ `ls /config/yggdrasil.$1.conf 2>/dev/null | wc -l` -gt 0 ];
    then
        echo -n "Starting yggdrasil interface $1... "
        setsid nice -5 /opt/vyatta/sbin/yggdrasil -useconffile /config/yggdrasil.$1.conf >/tmp/yggdrasil.$1.log & disown
        if [ $? -eq 0 ]; then echo "OK."; else echo "failed."; fi
    fi
else
    pgrep -f "yggdrasil -useconffile" | while read pid;
    do
        echo -n "Stopping yggdrasil interface $1... "
        kill $pid
        if [ $? -eq 0 ]; then echo "OK."; else echo "failed."; fi
    done

    if [ `ls /config/yggdrasil.*.conf 2>/dev/null | wc -l` -gt 0 ];
    then
        ls /config/yggdrasil.*.conf | awk -v FS="(yggdrasil.|.conf)" '{print $3}' | while read file;
        do
            echo -n "Starting yggdrasil interface $file... "
            setsid nice -5 /opt/vyatta/sbin/yggdrasil -useconffile /config/yggdrasil.$file.conf >/tmp/yggdrasil.$1.log & disown
            if [ $? -eq 0 ]; then echo "OK."; else echo "failed."; fi
        done
    fi
fi
