#!/bin/sh
#
# vyatta-yggdrasil - A yggdrasil package for Ubiquiti EdgeOS, VyOS and other
# Vyatta-based systems.
# Copyright (C) 2018 Neil Alexander T.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ -f /config/yggdrasil.$1.conf ]; then
	echo "yggdrasil generate conf: /config/yggdrasil.$1.conf already exists, leaving alone"
else
	echo "yggdrasil generate conf: $1"

	/opt/vyatta/sbin/yggdrasil -genconf > /config/yggdrasil.$1.conf
fi
