#!/usr/bin/python

import json
import sys

data = {}

with open('/config/yggdrasil.' + sys.argv[1] + '.conf') as data_file:
    data = json.load(data_file)

def setRequiredConfiguration(interface):
    if data['IfName'] != "none":
        data['IfName'] = interface
        data['IfTAPMode'] = False

def addPeer(peer):
    deletePeer(peer)
    data['Peers'].append(peer)

def deletePeer(peer):
    if peer in data['Peers']:
        data['Peers'].remove(peer)

def updateMulticast(enabled):
    data['Multicast'] = (enabled == "true")

try:
    if sys.argv[2] == "addPeer": addPeer(sys.argv[3])
    if sys.argv[2] == "deletePeer": deletePeer(sys.argv[3])
    if sys.argv[2] == "updateMulticast": updateMulticast(sys.argv[3])
except IndexError:
    print "Incorrect number of parameters supplied"
finally:
    setRequiredConfiguration(sys.argv[1])
    with open('/config/yggdrasil.' + sys.argv[1] + '.conf', 'w') as outfile:
        json.dump(data, outfile, indent=4)
